/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbcpr2;
import java.awt.Toolkit;
import java.sql.*;

/**
 *
 * @author User
 */
public class pr2_4 extends javax.swing.JFrame {

    /**
     * Creates new form pr2_4
     */
    public pr2_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMain = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        bllLname = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblFname1 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        lblConfirm = new javax.swing.JLabel();
        lblCache = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLoginRedirection = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirm = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMain.setFont(new java.awt.Font("Perpetua", 1, 60)); // NOI18N
        lblMain.setForeground(new java.awt.Color(255, 51, 51));
        lblMain.setText("Sign Up");
        jPanel1.add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        lblEmail.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        lblPassword.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 248, 33));

        btnRegister.setBackground(new java.awt.Color(0, 153, 0));
        btnRegister.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 679, 169, -1));

        bllLname.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        bllLname.setText("Last name");
        jPanel1.add(bllLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));
        jPanel1.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 248, 33));

        lblFname1.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        lblFname1.setText("First name");
        jPanel1.add(lblFname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));
        jPanel1.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 248, 33));

        lblConfirm.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        lblConfirm.setText("Confirm password");
        jPanel1.add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        lblCache.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCache.setText("It's free and takes a few minute");
        jPanel1.add(lblCache, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Already have an account ??");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 753, -1, -1));

        btnLoginRedirection.setBackground(new java.awt.Color(204, 204, 255));
        btnLoginRedirection.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLoginRedirection.setForeground(new java.awt.Color(51, 51, 255));
        btnLoginRedirection.setText("Login here");
        btnLoginRedirection.setContentAreaFilled(false);
        btnLoginRedirection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginRedirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginRedirectionActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginRedirection, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 750, -1, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 248, 33));
        jPanel1.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 248, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/signUp(1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("Welcome");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/java?user=root&password=******");
            System.out.println("Connection created!");

            String s = "insert into login(f_name, l_name, email, pwd) values(?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, txtFname.getText());
            ps.setString(2, txtLname.getText());
            ps.setString(3, txtEmail.getText());
            ps.setString(4, txtPassword.getText());
            ps.execute();

            System.out.println("Values inserted successfully\nSign up successful");
            con.close();
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println("Exception: "+e);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginRedirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginRedirectionActionPerformed
        // TODO add your handling code here:
        new pr2_7().setVisible(true);
    }//GEN-LAST:event_btnLoginRedirectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pr2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pr2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pr2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pr2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pr2_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bllLname;
    private javax.swing.JButton btnLoginRedirection;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCache;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
