/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbcpr2;
import javax.swing.Timer;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class pr2_8 extends javax.swing.JFrame {

    /**
     * Creates new form pr2_8
     */
    int point = 0;
    public pr2_8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question1 = new javax.swing.ButtonGroup();
        Question2 = new javax.swing.ButtonGroup();
        Question3 = new javax.swing.ButtonGroup();
        Question4 = new javax.swing.ButtonGroup();
        Question5 = new javax.swing.ButtonGroup();
        Question6 = new javax.swing.ButtonGroup();
        Question7 = new javax.swing.ButtonGroup();
        Question8 = new javax.swing.ButtonGroup();
        Question9 = new javax.swing.ButtonGroup();
        Question10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        q1 = new javax.swing.JPanel();
        lblQ1 = new javax.swing.JLabel();
        rdBtnQ1O1 = new javax.swing.JRadioButton();
        rdBtnQ1O2 = new javax.swing.JRadioButton();
        rdBtnQ1O3 = new javax.swing.JRadioButton();
        rdBtnQ1O4 = new javax.swing.JRadioButton();
        timer1 = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();
        btnPrevious1 = new javax.swing.JButton();
        BG1 = new javax.swing.JLabel();
        q2 = new javax.swing.JPanel();
        timer2 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        rdBtnQ2O1 = new javax.swing.JRadioButton();
        rdBtnQ2O2 = new javax.swing.JRadioButton();
        rdBtnQ2O3 = new javax.swing.JRadioButton();
        rdBtnQ2O4 = new javax.swing.JRadioButton();
        btnPrevious2 = new javax.swing.JButton();
        btnNext2 = new javax.swing.JButton();
        BG2 = new javax.swing.JLabel();
        q3 = new javax.swing.JPanel();
        timer3 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        rdBtnQ3O1 = new javax.swing.JRadioButton();
        rdBtnQ3O2 = new javax.swing.JRadioButton();
        rdBtnQ3O3 = new javax.swing.JRadioButton();
        rdBtnQ3O4 = new javax.swing.JRadioButton();
        btnPrevious3 = new javax.swing.JButton();
        btnNext3 = new javax.swing.JButton();
        BG3 = new javax.swing.JLabel();
        q4 = new javax.swing.JPanel();
        timer4 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        rdBtnQ4O1 = new javax.swing.JRadioButton();
        rdBtnQ4O2 = new javax.swing.JRadioButton();
        rdBtnQ4O3 = new javax.swing.JRadioButton();
        rdBtnQ4O4 = new javax.swing.JRadioButton();
        btnPrevious4 = new javax.swing.JButton();
        btnNext4 = new javax.swing.JButton();
        BG4 = new javax.swing.JLabel();
        q5 = new javax.swing.JPanel();
        timer5 = new javax.swing.JLabel();
        lblQ5 = new javax.swing.JLabel();
        rdBtnQ5O1 = new javax.swing.JRadioButton();
        rdBtnQ5O2 = new javax.swing.JRadioButton();
        rdBtnQ5O3 = new javax.swing.JRadioButton();
        rdBtnQ5O4 = new javax.swing.JRadioButton();
        btnPrevious5 = new javax.swing.JButton();
        btnNext5 = new javax.swing.JButton();
        BG5 = new javax.swing.JLabel();
        q6 = new javax.swing.JPanel();
        timer6 = new javax.swing.JLabel();
        lblQ6 = new javax.swing.JLabel();
        rdBtnQ6O1 = new javax.swing.JRadioButton();
        rdBtnQ6O2 = new javax.swing.JRadioButton();
        rdBtnQ6O3 = new javax.swing.JRadioButton();
        rdBtnQ6O4 = new javax.swing.JRadioButton();
        btnPrevious6 = new javax.swing.JButton();
        btnNext6 = new javax.swing.JButton();
        BG6 = new javax.swing.JLabel();
        q7 = new javax.swing.JPanel();
        timer7 = new javax.swing.JLabel();
        lblQ7 = new javax.swing.JLabel();
        rdBtnQ7O1 = new javax.swing.JRadioButton();
        rdBtnQ7O2 = new javax.swing.JRadioButton();
        rdBtnQ7O3 = new javax.swing.JRadioButton();
        rdBtnQ7O4 = new javax.swing.JRadioButton();
        btnPrevious7 = new javax.swing.JButton();
        btnNext7 = new javax.swing.JButton();
        BG7 = new javax.swing.JLabel();
        q8 = new javax.swing.JPanel();
        timer8 = new javax.swing.JLabel();
        lblQ8 = new javax.swing.JLabel();
        rdBtnQ8O1 = new javax.swing.JRadioButton();
        rdBtnQ8O2 = new javax.swing.JRadioButton();
        rdBtnQ8O3 = new javax.swing.JRadioButton();
        rdBtnQ8O4 = new javax.swing.JRadioButton();
        btnPrevious8 = new javax.swing.JButton();
        btnNext8 = new javax.swing.JButton();
        BG8 = new javax.swing.JLabel();
        q9 = new javax.swing.JPanel();
        timer9 = new javax.swing.JLabel();
        lblQ9 = new javax.swing.JLabel();
        rdBtnQ9O1 = new javax.swing.JRadioButton();
        rdBtnQ9O2 = new javax.swing.JRadioButton();
        rdBtnQ9O3 = new javax.swing.JRadioButton();
        rdBtnQ9O4 = new javax.swing.JRadioButton();
        btnPrevious9 = new javax.swing.JButton();
        btnNext9 = new javax.swing.JButton();
        BG9 = new javax.swing.JLabel();
        q10 = new javax.swing.JPanel();
        timer10 = new javax.swing.JLabel();
        lblQ10 = new javax.swing.JLabel();
        rdBtnQ10O1 = new javax.swing.JRadioButton();
        rdBtnQ10O2 = new javax.swing.JRadioButton();
        rdBtnQ10O3 = new javax.swing.JRadioButton();
        rdBtnQ10O4 = new javax.swing.JRadioButton();
        btnPrevious10 = new javax.swing.JButton();
        btnNext10 = new javax.swing.JButton();
        BG10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q1MouseClicked(evt);
            }
        });
        q1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQ1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblQ1.setForeground(new java.awt.Color(255, 255, 255));
        lblQ1.setText("Who invented Java Programming?");
        q1.add(lblQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 550, 110));

        Question1.add(rdBtnQ1O1);
        rdBtnQ1O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ1O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ1O1.setText("Guido van Rossum");
        rdBtnQ1O1.setContentAreaFilled(false);
        q1.add(rdBtnQ1O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 400, 50));

        Question1.add(rdBtnQ1O2);
        rdBtnQ1O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ1O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ1O2.setText("James Gosling");
        q1.add(rdBtnQ1O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 400, 50));

        Question1.add(rdBtnQ1O3);
        rdBtnQ1O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ1O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ1O3.setText("Dennis Ritchie");
        rdBtnQ1O3.setContentAreaFilled(false);
        rdBtnQ1O3.setFocusable(false);
        rdBtnQ1O3.setHideActionText(true);
        rdBtnQ1O3.setName(""); // NOI18N
        q1.add(rdBtnQ1O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 400, 50));

        Question1.add(rdBtnQ1O4);
        rdBtnQ1O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ1O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ1O4.setText("Bjarne Stroustrup");
        q1.add(rdBtnQ1O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 400, 50));

        timer1.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer1.setForeground(new java.awt.Color(255, 255, 255));
        timer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q1.add(timer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 40, 40));

        btnNext1.setText("Next");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        q1.add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 80, 30));

        btnPrevious1.setText("Previous");
        btnPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious1ActionPerformed(evt);
            }
        });
        q1.add(btnPrevious1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 80, 30));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q1.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question1", q1);

        q2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q2MouseClicked(evt);
            }
        });
        q2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer2.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer2.setForeground(new java.awt.Color(255, 255, 255));
        timer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q2.add(timer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 40, 40));

        lblQ2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQ2.setForeground(new java.awt.Color(255, 255, 255));
        lblQ2.setText("Which component is used to compile,\n debug and execute the java programs?");
        q2.add(lblQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        Question2.add(rdBtnQ2O1);
        rdBtnQ2O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ2O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ2O1.setText("JRE");
        q2.add(rdBtnQ2O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question2.add(rdBtnQ2O2);
        rdBtnQ2O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ2O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ2O2.setText("JIT");
        q2.add(rdBtnQ2O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question2.add(rdBtnQ2O3);
        rdBtnQ2O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ2O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ2O3.setText("JDK");
        q2.add(rdBtnQ2O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question2.add(rdBtnQ2O4);
        rdBtnQ2O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ2O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ2O4.setText("JVM");
        q2.add(rdBtnQ2O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious2.setText("Previous");
        btnPrevious2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious2ActionPerformed(evt);
            }
        });
        q2.add(btnPrevious2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, 30));

        btnNext2.setText("Next");
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });
        q2.add(btnNext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 80, 30));

        BG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q2.add(BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question2", q2);

        q3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q3MouseClicked(evt);
            }
        });
        q3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer3.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer3.setForeground(new java.awt.Color(255, 255, 255));
        timer3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q3.add(timer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 39, 36));

        lblQ3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQ3.setForeground(new java.awt.Color(255, 255, 255));
        lblQ3.setText("Which of the following is not an OOPS concept in Java?");
        q3.add(lblQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 610, 70));

        Question3.add(rdBtnQ3O1);
        rdBtnQ3O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ3O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ3O1.setText("Polymorphism");
        q3.add(rdBtnQ3O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question3.add(rdBtnQ3O2);
        rdBtnQ3O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ3O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ3O2.setText("Inheritance");
        q3.add(rdBtnQ3O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question3.add(rdBtnQ3O3);
        rdBtnQ3O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ3O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ3O3.setText("Compilation");
        q3.add(rdBtnQ3O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question3.add(rdBtnQ3O4);
        rdBtnQ3O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ3O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ3O4.setText("Encapsulation");
        q3.add(rdBtnQ3O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious3.setText("Previous");
        btnPrevious3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious3ActionPerformed(evt);
            }
        });
        q3.add(btnPrevious3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, 30));

        btnNext3.setText("Next");
        btnNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext3ActionPerformed(evt);
            }
        });
        q3.add(btnNext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, 30));

        BG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q3.add(BG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question3", q3);

        q4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q4MouseClicked(evt);
            }
        });
        q4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer4.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer4.setForeground(new java.awt.Color(255, 255, 255));
        timer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q4.add(timer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 40, 40));

        lblQ4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQ4.setForeground(new java.awt.Color(255, 255, 255));
        lblQ4.setText("What is the extension of compiled java classes?");
        q4.add(lblQ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        Question4.add(rdBtnQ4O1);
        rdBtnQ4O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ4O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ4O1.setText(".txt");
        q4.add(rdBtnQ4O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question4.add(rdBtnQ4O2);
        rdBtnQ4O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ4O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ4O2.setText(".js");
        q4.add(rdBtnQ4O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question4.add(rdBtnQ4O3);
        rdBtnQ4O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ4O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ4O3.setText(".class");
        q4.add(rdBtnQ4O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question4.add(rdBtnQ4O4);
        rdBtnQ4O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ4O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ4O4.setText(".java");
        q4.add(rdBtnQ4O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious4.setText("Previous");
        btnPrevious4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious4ActionPerformed(evt);
            }
        });
        q4.add(btnPrevious4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, 30));

        btnNext4.setText("Next");
        btnNext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext4ActionPerformed(evt);
            }
        });
        q4.add(btnNext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 80, 30));

        BG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q4.add(BG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question4", q4);

        q5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q5MouseClicked(evt);
            }
        });
        q5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer5.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer5.setForeground(new java.awt.Color(255, 255, 255));
        timer5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q5.add(timer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 40, 40));

        lblQ5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQ5.setForeground(new java.awt.Color(255, 255, 255));
        lblQ5.setText("Which exception is thrown when java is out of memory?");
        q5.add(lblQ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        Question5.add(rdBtnQ5O1);
        rdBtnQ5O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ5O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ5O1.setText("MemoryError");
        q5.add(rdBtnQ5O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question5.add(rdBtnQ5O2);
        rdBtnQ5O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ5O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ5O2.setText("OutOfMemoryError");
        q5.add(rdBtnQ5O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question5.add(rdBtnQ5O3);
        rdBtnQ5O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ5O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ5O3.setText("MemoryOutOfBoundsException");
        q5.add(rdBtnQ5O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question5.add(rdBtnQ5O4);
        rdBtnQ5O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ5O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ5O4.setText("MemoryFullException");
        q5.add(rdBtnQ5O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious5.setText("Previous");
        btnPrevious5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious5ActionPerformed(evt);
            }
        });
        q5.add(btnPrevious5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, 30));

        btnNext5.setText("Next");
        btnNext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext5ActionPerformed(evt);
            }
        });
        q5.add(btnNext5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 80, 30));

        BG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q5.add(BG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question5", q5);

        q6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q6MouseClicked(evt);
            }
        });
        q6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer6.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer6.setForeground(new java.awt.Color(255, 255, 255));
        timer6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q6.add(timer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 40, 40));

        lblQ6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQ6.setForeground(new java.awt.Color(255, 255, 255));
        lblQ6.setText("Which of the following is a superclass of every class in Java?");
        q6.add(lblQ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 650, 40));

        Question6.add(rdBtnQ6O1);
        rdBtnQ6O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ6O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ6O1.setText("ArrayList");
        q6.add(rdBtnQ6O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question6.add(rdBtnQ6O2);
        rdBtnQ6O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ6O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ6O2.setText("Abstract class");
        q6.add(rdBtnQ6O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question6.add(rdBtnQ6O3);
        rdBtnQ6O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ6O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ6O3.setText("Object class");
        q6.add(rdBtnQ6O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question6.add(rdBtnQ6O4);
        rdBtnQ6O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ6O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ6O4.setText("String");
        q6.add(rdBtnQ6O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious6.setText("Previous");
        btnPrevious6.setBorder(null);
        btnPrevious6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious6ActionPerformed(evt);
            }
        });
        q6.add(btnPrevious6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 70, 30));

        btnNext6.setText("Next");
        btnNext6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext6ActionPerformed(evt);
            }
        });
        q6.add(btnNext6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, 30));

        BG6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q6.add(BG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question6", q6);

        q7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q7MouseClicked(evt);
            }
        });
        q7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer7.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer7.setForeground(new java.awt.Color(255, 255, 255));
        timer7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q7.add(timer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 40, 40));

        lblQ7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQ7.setForeground(new java.awt.Color(255, 255, 255));
        lblQ7.setText("Which one of the following is not an access modifier?");
        q7.add(lblQ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, 40));

        Question7.add(rdBtnQ7O1);
        rdBtnQ7O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ7O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ7O1.setText("Protected");
        q7.add(rdBtnQ7O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 390, 60));

        Question7.add(rdBtnQ7O2);
        rdBtnQ7O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ7O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ7O2.setText("Void");
        q7.add(rdBtnQ7O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question7.add(rdBtnQ7O3);
        rdBtnQ7O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ7O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ7O3.setText("Public");
        q7.add(rdBtnQ7O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question7.add(rdBtnQ7O4);
        rdBtnQ7O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ7O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ7O4.setText("Private");
        q7.add(rdBtnQ7O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious7.setText("Previous");
        btnPrevious7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious7ActionPerformed(evt);
            }
        });
        q7.add(btnPrevious7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 80, 30));

        btnNext7.setText("Next");
        btnNext7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext7ActionPerformed(evt);
            }
        });
        q7.add(btnNext7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 80, 30));

        BG7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q7.add(BG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question7", q7);

        q8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q8MouseClicked(evt);
            }
        });
        q8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer8.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer8.setForeground(new java.awt.Color(255, 255, 255));
        timer8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q8.add(timer8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 40, 40));

        lblQ8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblQ8.setForeground(new java.awt.Color(255, 255, 255));
        lblQ8.setText("Which class provides system independent server side implementation?");
        q8.add(lblQ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        Question8.add(rdBtnQ8O1);
        rdBtnQ8O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ8O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ8O1.setText("Server");
        q8.add(rdBtnQ8O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question8.add(rdBtnQ8O2);
        rdBtnQ8O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ8O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ8O2.setText("ServerReader");
        q8.add(rdBtnQ8O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question8.add(rdBtnQ8O3);
        rdBtnQ8O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ8O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ8O3.setText("Socket");
        q8.add(rdBtnQ8O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question8.add(rdBtnQ8O4);
        rdBtnQ8O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ8O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ8O4.setText("ServerSocket");
        q8.add(rdBtnQ8O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious8.setText("Previous");
        btnPrevious8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious8ActionPerformed(evt);
            }
        });
        q8.add(btnPrevious8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 80, 30));

        btnNext8.setText("Next");
        btnNext8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext8ActionPerformed(evt);
            }
        });
        q8.add(btnNext8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 80, 30));

        BG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q8.add(BG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question8", q8);

        q9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q9MouseClicked(evt);
            }
        });
        q9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer9.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer9.setForeground(new java.awt.Color(255, 255, 255));
        timer9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q9.add(timer9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 40, 40));

        lblQ9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQ9.setForeground(new java.awt.Color(255, 255, 255));
        lblQ9.setText("Which of the following can be operands of arithmetic operators?");
        q9.add(lblQ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        Question9.add(rdBtnQ9O1);
        rdBtnQ9O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ9O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ9O1.setText("Numeric");
        q9.add(rdBtnQ9O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question9.add(rdBtnQ9O2);
        rdBtnQ9O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ9O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ9O2.setText("Boolean");
        q9.add(rdBtnQ9O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question9.add(rdBtnQ9O3);
        rdBtnQ9O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ9O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ9O3.setText("Characters");
        q9.add(rdBtnQ9O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question9.add(rdBtnQ9O4);
        rdBtnQ9O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ9O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ9O4.setText("Both Numeric & Characters");
        q9.add(rdBtnQ9O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious9.setText("Previous");
        btnPrevious9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious9ActionPerformed(evt);
            }
        });
        q9.add(btnPrevious9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 80, 30));

        btnNext9.setText("Next");
        btnNext9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext9ActionPerformed(evt);
            }
        });
        q9.add(btnNext9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 80, 30));

        BG9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q9.add(BG9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question9", q9);

        q10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q10MouseClicked(evt);
            }
        });
        q10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer10.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        timer10.setForeground(new java.awt.Color(255, 255, 255));
        timer10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        q10.add(timer10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 40, 40));

        lblQ10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQ10.setForeground(new java.awt.Color(255, 255, 255));
        lblQ10.setText("Which page directive should be used in JSP to generate a PDF page?");
        q10.add(lblQ10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, 40));

        Question10.add(rdBtnQ10O1);
        rdBtnQ10O1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ10O1.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ10O1.setText("contentType");
        q10.add(rdBtnQ10O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 400, 60));

        Question10.add(rdBtnQ10O2);
        rdBtnQ10O2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ10O2.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ10O2.setText("generatePdf");
        q10.add(rdBtnQ10O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 400, 60));

        Question10.add(rdBtnQ10O3);
        rdBtnQ10O3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ10O3.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ10O3.setText("typePDF");
        q10.add(rdBtnQ10O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 400, 60));

        Question10.add(rdBtnQ10O4);
        rdBtnQ10O4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdBtnQ10O4.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnQ10O4.setText("contentPDF");
        q10.add(rdBtnQ10O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 400, 60));

        btnPrevious10.setText("Previous");
        btnPrevious10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious10ActionPerformed(evt);
            }
        });
        q10.add(btnPrevious10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, 30));

        btnNext10.setText("Submit");
        btnNext10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext10ActionPerformed(evt);
            }
        });
        q10.add(btnNext10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, 30));

        BG10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/question(3).jpg"))); // NOI18N
        q10.add(BG10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Question10", q10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q1MouseClicked
        // TODO add your handling code here:
        t1.start();
    }//GEN-LAST:event_q1MouseClicked

    private void q2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q2MouseClicked
        // TODO add your handling code here:
        t2.start();
    }//GEN-LAST:event_q2MouseClicked

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        rdBtnQ1O1.setActionCommand("Guido Van Roseum");
        rdBtnQ1O2.setActionCommand("James Gosling");
        rdBtnQ1O3.setActionCommand("Dennis Ritchie");
        rdBtnQ1O4.setActionCommand("Bjarne Stroustrup");
        System.out.println("Selected radiobutton for Question1 is:"+Question1.getSelection().getActionCommand());
        if("James Gosling".equals(Question1.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext1.setEnabled(false);
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnPrevious1ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        rdBtnQ2O1.setActionCommand("JRE");
        rdBtnQ2O2.setActionCommand("JIT");
        rdBtnQ2O3.setActionCommand("JDK");
        rdBtnQ2O4.setActionCommand("JVM");
        System.out.println("Selected radiobutton for Question2 is:"+Question2.getSelection().getActionCommand());
        if("JDK".equals(Question2.getSelection().getActionCommand()))
        {
            point = point+10;
            System.out.println(point);
        }
        btnNext2.setEnabled(false);
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnPrevious2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnPrevious2ActionPerformed

    private void q3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q3MouseClicked
        // TODO add your handling code here:
        t3.start();
    }//GEN-LAST:event_q3MouseClicked

    private void btnPrevious3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnPrevious3ActionPerformed

    private void btnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        rdBtnQ3O1.setActionCommand("Polymorphism");
        rdBtnQ3O2.setActionCommand("Inheritance");
        rdBtnQ3O3.setActionCommand("Compilation");
        rdBtnQ3O4.setActionCommand("Encapsulation");
        System.out.println("Selected radiobutton for Question3 is:"+Question3.getSelection().getActionCommand());
        if("Compilation".equals(Question3.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext3.setEnabled(false);
    }//GEN-LAST:event_btnNext3ActionPerformed

    private void q4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q4MouseClicked
        // TODO add your handling code here:
        t4.start();
    }//GEN-LAST:event_q4MouseClicked

    private void btnPrevious4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnPrevious4ActionPerformed

    private void btnNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        rdBtnQ4O1.setActionCommand(".txt");
        rdBtnQ4O2.setActionCommand(".js");
        rdBtnQ4O3.setActionCommand(".class");
        rdBtnQ4O4.setActionCommand(".java");
        System.out.println("Selected radiobutton for Question4 is:"+Question4.getSelection().getActionCommand());
        if(".class".equals(Question4.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext4.setEnabled(false);
    }//GEN-LAST:event_btnNext4ActionPerformed

    private void q5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q5MouseClicked
        // TODO add your handling code here:
        t5.start();
    }//GEN-LAST:event_q5MouseClicked

    private void btnPrevious5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnPrevious5ActionPerformed

    private void btnNext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
        rdBtnQ5O1.setActionCommand("MemoryError");
        rdBtnQ5O2.setActionCommand("OutOfMemoryError");
        rdBtnQ5O3.setActionCommand("MemoryOutOfBoundsException");
        rdBtnQ5O4.setActionCommand("MemoryFullException");
        System.out.println("Selected radiobutton for Question5 is:"+Question5.getSelection().getActionCommand());
        if("OutOfMemoryError".equals(Question5.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext5.setEnabled(false);
    }//GEN-LAST:event_btnNext5ActionPerformed

    private void q6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q6MouseClicked
        // TODO add your handling code here:
        t6.start();
    }//GEN-LAST:event_q6MouseClicked

    private void btnPrevious6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnPrevious6ActionPerformed

    private void btnNext6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
        rdBtnQ6O1.setActionCommand("ArrayList");
        rdBtnQ6O2.setActionCommand("Abstract class");
        rdBtnQ6O3.setActionCommand("Object class");
        rdBtnQ6O4.setActionCommand("String");
        System.out.println("Selected radiobutton for Question6 is:"+Question6.getSelection().getActionCommand());
        if("Object class".equals(Question6.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext6.setEnabled(false);
    }//GEN-LAST:event_btnNext6ActionPerformed

    private void q7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q7MouseClicked
        // TODO add your handling code here:
        t7.start();
    }//GEN-LAST:event_q7MouseClicked

    private void btnPrevious7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_btnPrevious7ActionPerformed

    private void btnNext7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
        rdBtnQ7O1.setActionCommand("Protected");
        rdBtnQ7O2.setActionCommand("Void");
        rdBtnQ7O3.setActionCommand("Public");
        rdBtnQ7O4.setActionCommand("Private");
        System.out.println("Selected radiobutton for Question7 is:"+Question7.getSelection().getActionCommand());
        if("Void".equals(Question7.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext7.setEnabled(false);
    }//GEN-LAST:event_btnNext7ActionPerformed

    private void q8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q8MouseClicked
        // TODO add your handling code here:
        t8.start();
    }//GEN-LAST:event_q8MouseClicked

    private void btnPrevious8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious8ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_btnPrevious8ActionPerformed

    private void btnNext8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext8ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(8);
        rdBtnQ8O1.setActionCommand("Server");
        rdBtnQ8O2.setActionCommand("ServerReader");
        rdBtnQ8O3.setActionCommand("Socket");
        rdBtnQ8O4.setActionCommand("ServerSocket");
        System.out.println("Selected radiobutton for Question8 is:"+Question8.getSelection().getActionCommand());
        if("ServerSocket".equals(Question8.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext8.setEnabled(false);
    }//GEN-LAST:event_btnNext8ActionPerformed

    private void q9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q9MouseClicked
        // TODO add your handling code here:
        t9.start();
    }//GEN-LAST:event_q9MouseClicked

    private void btnPrevious9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious9ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_btnPrevious9ActionPerformed

    private void btnNext9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext9ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(9);
        rdBtnQ9O1.setActionCommand("Numeric");
        rdBtnQ9O2.setActionCommand("Boolean");
        rdBtnQ9O3.setActionCommand("Characters");
        rdBtnQ9O4.setActionCommand("Both Numeric & Characters");
        System.out.println("Selected radiobutton for Question9 is:"+Question9.getSelection().getActionCommand());
        if("Both Numeric & Characters".equals(Question9.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        btnNext9.setEnabled(false);
    }//GEN-LAST:event_btnNext9ActionPerformed

    private void q10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q10MouseClicked
        // TODO add your handling code here:
        t10.start();
    }//GEN-LAST:event_q10MouseClicked

    private void btnPrevious10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious10ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(8);
    }//GEN-LAST:event_btnPrevious10ActionPerformed

    private void btnNext10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext10ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(9);
        rdBtnQ10O1.setActionCommand("contentType");
        rdBtnQ10O2.setActionCommand("generatePdf");
        rdBtnQ10O3.setActionCommand("typePDF");
        rdBtnQ10O4.setActionCommand("contentPDF");
        System.out.println("Selected radiobutton for Question10 is:"+Question10.getSelection().getActionCommand());
        if("contentType".equals(Question10.getSelection().getActionCommand())){
            point = point+10;
            System.out.println(point);
        }
        else
            System.out.println(point);
        btnNext10.setEnabled(false);
        new pr2_9().setVisible(true);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("Welcome");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/java?user=root&password=$ahil2003");
            System.out.println("Connection created!");
            
            String s = "insert into score(name, points) values(?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, "Sahil");
            ps.setInt(2, point);
            ps.execute();

            System.out.println("Values inserted successfully");
            con.close();
        }
        catch(ClassNotFoundException | SQLException e){
           System.out.println("Exception: "+e);
        }
    }//GEN-LAST:event_btnNext10ActionPerformed
    
    Timer t1 = new Timer(1000, new ActionListner()
    {
        int i1 = 11;
        public void actionPerformed(ActionEvent e){
            i1--;
            if(i1>=0){
                timer1.setText(""+i1);
            }
            if(i1==0)
            {
                jTabbedPane1.setSelectedIndex(1);
                rdBtnQ1O1.setEnabled(false);
                rdBtnQ1O2.setEnabled(false);
                rdBtnQ1O3.setEnabled(false);
                rdBtnQ1O4.setEnabled(false);
                rdBtnQ1O1.setActionCommand("Guido Van Roseum");
                rdBtnQ1O2.setActionCommand("James Gosling");
                rdBtnQ1O3.setActionCommand("Dennis Ritchie");
                rdBtnQ1O4.setActionCommand("Bjarne Stroustrup");
                System.out.println("Selected radiobutton for Question1 is:"+Question1.getSelection().getActionCommand());
                if("James Gosling".equals(Question1.getSelection().getActionCommand()))
                {
                    point = point+10;
                    System.out.println(point);
                }
                btnNext1.setEnabled(false);
            }            
        }
    });
    Timer t2 = new Timer(1000, new ActionListner()
    {
        int i2 = 11;
        public void actionPerformed(ActionEvent e){
            i2--;
            if(i2>=0){
                timer2.setText(""+i2);
            }
            if(i2==0)
            {
                jTabbedPane1.setSelectedIndex(2);
                rdBtnQ2O1.setEnabled(false);
                rdBtnQ2O2.setEnabled(false);
                rdBtnQ2O3.setEnabled(false);
                rdBtnQ2O4.setEnabled(false);
                rdBtnQ2O1.setActionCommand("JRE");
                rdBtnQ2O2.setActionCommand("JIT");
                rdBtnQ2O3.setActionCommand("JDK");
                rdBtnQ2O4.setActionCommand("JVM");
                System.out.println("Selected radiobutton for Question2 is:"+Question2.getSelection().getActionCommand());
                if("JDK".equals(Question2.getSelection().getActionCommand()))
                {
                    point = point+10;
                    System.out.println(point);
                }
                btnNext2.setEnabled(false);
            }
        }
    });
    Timer t3 = new Timer(1000, new ActionListner()
    {
        int i3 = 11;
        public void actionPerformed(ActionEvent e){
            i3--;
            if(i3>=0){
                timer3.setText(""+i3);
            }
            if(i3==0)
            {
                jTabbedPane1.setSelectedIndex(3);
                rdBtnQ3O1.setEnabled(false);
                rdBtnQ3O2.setEnabled(false);
                rdBtnQ3O3.setEnabled(false);
                rdBtnQ3O4.setEnabled(false);
                rdBtnQ3O1.setActionCommand("Polymorphism");
                rdBtnQ3O2.setActionCommand("Inheritance");
                rdBtnQ3O3.setActionCommand("Compilation");
                rdBtnQ3O4.setActionCommand("Encapsulation");
                System.out.println("Selected radiobutton for Question3 is:"+Question3.getSelection().getActionCommand());
                if("Compilation".equals(Question3.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                btnNext3.setEnabled(false);
            }            
        }
    });
    Timer t4 = new Timer(1000, new ActionListner()
    {
        int i4 = 11;
        public void actionPerformed(ActionEvent e){
            i4--;
            if(i4>=0){
                timer4.setText(""+i4);
            }
            if(i4==0)
            {
                jTabbedPane1.setSelectedIndex(4);
                rdBtnQ4O1.setEnabled(false);
                rdBtnQ4O2.setEnabled(false);
                rdBtnQ4O3.setEnabled(false);
                rdBtnQ4O4.setEnabled(false);
                rdBtnQ4O1.setActionCommand(".txt");
                rdBtnQ4O2.setActionCommand(".js");
                rdBtnQ4O3.setActionCommand(".class");
                rdBtnQ4O4.setActionCommand(".java");
                System.out.println("Selected radiobutton for Question4 is:"+Question4.getSelection().getActionCommand());
                if(".class".equals(Question4.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                btnNext4.setEnabled(false);
            }            
        }
    });
    Timer t5 = new Timer(1000, new ActionListner()
    {
        int i5 = 11;
        @Override
        public void actionPerformed(ActionEvent e){
            i5--;
            if(i5>=0){
                timer5.setText(""+i5);
            }
            if(i5==0)
            {
                jTabbedPane1.setSelectedIndex(5);
                rdBtnQ5O1.setEnabled(false);
                rdBtnQ5O2.setEnabled(false);
                rdBtnQ5O3.setEnabled(false);
                rdBtnQ5O4.setEnabled(false);
                rdBtnQ5O1.setActionCommand("MemoryError");
                rdBtnQ5O2.setActionCommand("OutOfMemoryError");
                rdBtnQ5O3.setActionCommand("MemoryOutOfBoundsException");
                rdBtnQ5O4.setActionCommand("MemoryFullException");
                System.out.println("Selected radiobutton for Question5 is:"+Question5.getSelection().getActionCommand());
                if("OutOfMemoryError".equals(Question5.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                btnNext5.setEnabled(false);
            }            
        }
    });
    Timer t6 = new Timer(1000, new ActionListner()
    {
        int i6 = 11;
        @Override
        public void actionPerformed(ActionEvent e){
            i6--;
            if(i6>=0){
                timer6.setText(""+i6);
            }
            if(i6==0)
            {
                jTabbedPane1.setSelectedIndex(6);
                rdBtnQ6O1.setEnabled(false);
                rdBtnQ6O2.setEnabled(false);
                rdBtnQ6O3.setEnabled(false);
                rdBtnQ6O4.setEnabled(false);
                rdBtnQ6O1.setActionCommand("ArrayList");
                rdBtnQ6O2.setActionCommand("Abstract class");
                rdBtnQ6O3.setActionCommand("Object class");
                rdBtnQ6O4.setActionCommand("String");
                System.out.println("Selected radiobutton for Question6 is:"+Question6.getSelection().getActionCommand());
                if("Object class".equals(Question6.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                btnNext6.setEnabled(false);
            }            
        }
    });
    Timer t7 = new Timer(1000, new ActionListner()
    {
        int i7 = 11;
        @Override
        public void actionPerformed(ActionEvent e){
            i7--;
            if(i7>=0){
                timer7.setText(""+i7);
            }
            if(i7==0)
            {
                jTabbedPane1.setSelectedIndex(7);
                rdBtnQ7O1.setEnabled(false);
                rdBtnQ7O2.setEnabled(false);
                rdBtnQ7O3.setEnabled(false);
                rdBtnQ7O4.setEnabled(false);
                rdBtnQ7O1.setActionCommand("Protected");
                rdBtnQ7O2.setActionCommand("Void");
                rdBtnQ7O3.setActionCommand("Public");
                rdBtnQ7O4.setActionCommand("Private");
                System.out.println("Selected radiobutton for Question7 is:"+Question7.getSelection().getActionCommand());
                if("Void".equals(Question7.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                btnNext7.setEnabled(false);
            }            
        }
    });
    Timer t8 = new Timer(1000, new ActionListner()
    {
        int i8 = 11;
        @Override
        public void actionPerformed(ActionEvent e){
            i8--;
            if(i8>=0){
                timer8.setText(""+i8);
            }
            if(i8==0)
            {
                jTabbedPane1.setSelectedIndex(8);
                rdBtnQ8O1.setEnabled(false);
                rdBtnQ8O2.setEnabled(false);
                rdBtnQ8O3.setEnabled(false);
                rdBtnQ8O4.setEnabled(false);
                rdBtnQ8O1.setActionCommand("Server");
                rdBtnQ8O2.setActionCommand("ServerReader");
                rdBtnQ8O3.setActionCommand("Socket");
                rdBtnQ8O4.setActionCommand("ServerSocket");
                System.out.println("Selected radiobutton for Question8 is:"+Question8.getSelection().getActionCommand());
                if("ServerSocket".equals(Question8.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                btnNext8.setEnabled(false);
            }            
        }
    });
    Timer t9 = new Timer(1000, new ActionListner()
    {
        int i9 = 11;
        public void actionPerformed(ActionEvent e){
            i9--;
            if(i9>=0){
                timer9.setText(""+i9);
            }
            if(i9==0)
            {
                jTabbedPane1.setSelectedIndex(9);
                rdBtnQ9O1.setEnabled(false);
                rdBtnQ9O2.setEnabled(false);
                rdBtnQ9O3.setEnabled(false);
                rdBtnQ9O4.setEnabled(false);
                rdBtnQ9O1.setActionCommand("Numeric");
                rdBtnQ9O2.setActionCommand("Boolean");
                rdBtnQ9O3.setActionCommand("Characters");
                rdBtnQ9O4.setActionCommand("Both Numeric & Characters");
                System.out.println("Selected radiobutton for Question9 is:"+Question9.getSelection().getActionCommand());
                if("Both Numeric & Characters".equals(Question9.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                btnNext9.setEnabled(false);
            }            
        }
    });
    Timer t10 = new Timer(1000, new ActionListner()
    {
        int i10 = 11;
        public void actionPerformed(ActionEvent e){
            i10--;
            if(i10>=0){
                timer10.setText(""+i10);
            }
            if(i10==0)
            {
                jTabbedPane1.setSelectedIndex(9);
                rdBtnQ10O1.setEnabled(false);
                rdBtnQ10O2.setEnabled(false);
                rdBtnQ10O3.setEnabled(false);
                rdBtnQ10O4.setEnabled(false);
                rdBtnQ10O1.setActionCommand("contentType");
                rdBtnQ10O2.setActionCommand("generatePdf");
                rdBtnQ10O3.setActionCommand("typePDF");
                rdBtnQ10O4.setActionCommand("contentPDF");
                System.out.println("Selected radiobutton for Question10 is:"+Question10.getSelection().getActionCommand());
                if("contentType".equals(Question10.getSelection().getActionCommand())){
                    point = point+10;
                    System.out.println(point);
                }
                else
                    System.out.println(point);
            }
            else if(i10 == 2){
                rdBtnQ10O3.setSelected(true);
            }
        }
    });
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pr2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pr2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pr2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pr2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pr2_8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel BG10;
    private javax.swing.JLabel BG2;
    private javax.swing.JLabel BG3;
    private javax.swing.JLabel BG4;
    private javax.swing.JLabel BG5;
    private javax.swing.JLabel BG6;
    private javax.swing.JLabel BG7;
    private javax.swing.JLabel BG8;
    private javax.swing.JLabel BG9;
    private javax.swing.ButtonGroup Question1;
    private javax.swing.ButtonGroup Question10;
    private javax.swing.ButtonGroup Question2;
    private javax.swing.ButtonGroup Question3;
    private javax.swing.ButtonGroup Question4;
    private javax.swing.ButtonGroup Question5;
    private javax.swing.ButtonGroup Question6;
    private javax.swing.ButtonGroup Question7;
    private javax.swing.ButtonGroup Question8;
    private javax.swing.ButtonGroup Question9;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext10;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnNext3;
    private javax.swing.JButton btnNext4;
    private javax.swing.JButton btnNext5;
    private javax.swing.JButton btnNext6;
    private javax.swing.JButton btnNext7;
    private javax.swing.JButton btnNext8;
    private javax.swing.JButton btnNext9;
    private javax.swing.JButton btnPrevious1;
    private javax.swing.JButton btnPrevious10;
    private javax.swing.JButton btnPrevious2;
    private javax.swing.JButton btnPrevious3;
    private javax.swing.JButton btnPrevious4;
    private javax.swing.JButton btnPrevious5;
    private javax.swing.JButton btnPrevious6;
    private javax.swing.JButton btnPrevious7;
    private javax.swing.JButton btnPrevious8;
    private javax.swing.JButton btnPrevious9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ10;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ6;
    private javax.swing.JLabel lblQ7;
    private javax.swing.JLabel lblQ8;
    private javax.swing.JLabel lblQ9;
    private javax.swing.JPanel q1;
    private javax.swing.JPanel q10;
    private javax.swing.JPanel q2;
    private javax.swing.JPanel q3;
    private javax.swing.JPanel q4;
    private javax.swing.JPanel q5;
    private javax.swing.JPanel q6;
    private javax.swing.JPanel q7;
    private javax.swing.JPanel q8;
    private javax.swing.JPanel q9;
    private javax.swing.JRadioButton rdBtnQ10O1;
    private javax.swing.JRadioButton rdBtnQ10O2;
    private javax.swing.JRadioButton rdBtnQ10O3;
    private javax.swing.JRadioButton rdBtnQ10O4;
    private javax.swing.JRadioButton rdBtnQ1O1;
    private javax.swing.JRadioButton rdBtnQ1O2;
    private javax.swing.JRadioButton rdBtnQ1O3;
    private javax.swing.JRadioButton rdBtnQ1O4;
    private javax.swing.JRadioButton rdBtnQ2O1;
    private javax.swing.JRadioButton rdBtnQ2O2;
    private javax.swing.JRadioButton rdBtnQ2O3;
    private javax.swing.JRadioButton rdBtnQ2O4;
    private javax.swing.JRadioButton rdBtnQ3O1;
    private javax.swing.JRadioButton rdBtnQ3O2;
    private javax.swing.JRadioButton rdBtnQ3O3;
    private javax.swing.JRadioButton rdBtnQ3O4;
    private javax.swing.JRadioButton rdBtnQ4O1;
    private javax.swing.JRadioButton rdBtnQ4O2;
    private javax.swing.JRadioButton rdBtnQ4O3;
    private javax.swing.JRadioButton rdBtnQ4O4;
    private javax.swing.JRadioButton rdBtnQ5O1;
    private javax.swing.JRadioButton rdBtnQ5O2;
    private javax.swing.JRadioButton rdBtnQ5O3;
    private javax.swing.JRadioButton rdBtnQ5O4;
    private javax.swing.JRadioButton rdBtnQ6O1;
    private javax.swing.JRadioButton rdBtnQ6O2;
    private javax.swing.JRadioButton rdBtnQ6O3;
    private javax.swing.JRadioButton rdBtnQ6O4;
    private javax.swing.JRadioButton rdBtnQ7O1;
    private javax.swing.JRadioButton rdBtnQ7O2;
    private javax.swing.JRadioButton rdBtnQ7O3;
    private javax.swing.JRadioButton rdBtnQ7O4;
    private javax.swing.JRadioButton rdBtnQ8O1;
    private javax.swing.JRadioButton rdBtnQ8O2;
    private javax.swing.JRadioButton rdBtnQ8O3;
    private javax.swing.JRadioButton rdBtnQ8O4;
    private javax.swing.JRadioButton rdBtnQ9O1;
    private javax.swing.JRadioButton rdBtnQ9O2;
    private javax.swing.JRadioButton rdBtnQ9O3;
    private javax.swing.JRadioButton rdBtnQ9O4;
    private javax.swing.JLabel timer1;
    private javax.swing.JLabel timer10;
    private javax.swing.JLabel timer2;
    private javax.swing.JLabel timer3;
    private javax.swing.JLabel timer4;
    private javax.swing.JLabel timer5;
    private javax.swing.JLabel timer6;
    private javax.swing.JLabel timer7;
    private javax.swing.JLabel timer8;
    private javax.swing.JLabel timer9;
    // End of variables declaration//GEN-END:variables

    private static class ActionListner implements ActionListener {

        public ActionListner() {
            
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
