/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbcpr2;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */

public class pr2_7 extends javax.swing.JFrame {

    /**
     * Creates new form pr2_7
     */
    public pr2_7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSignUpRedirection = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(785, 563));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMain.setFont(new java.awt.Font("Perpetua", 1, 60)); // NOI18N
        lblMain.setForeground(new java.awt.Color(255, 51, 51));
        lblMain.setText("Sign In");
        getContentPane().add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        lblEmail.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 248, 33));

        lblPassword.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 248, 33));

        btnLogin.setBackground(new java.awt.Color(0, 153, 0));
        btnLogin.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 169, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("New user ??");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        btnSignUpRedirection.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignUpRedirection.setForeground(new java.awt.Color(51, 51, 255));
        btnSignUpRedirection.setText("SignUp");
        btnSignUpRedirection.setContentAreaFilled(false);
        btnSignUpRedirection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUpRedirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpRedirectionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUpRedirection, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcpr2/signUp(2).png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String u = txtEmail.getText();
        String queryname = ""+txtEmail.getText()+"";
        char[] c = txtPassword.getPassword();
        String p = String.valueOf(c);
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/java?user=root&password=$ahil2003");
            
            Statement st = con.createStatement();
            //String query = "select email,pwd from login where email="+queryname+"";
            
            ResultSet rst = st.executeQuery("select email,pwd from login where email="+queryname+"");
            
            while(rst.next()){
                String uname = rst.getString("uname");
                String passs = rst.getString("passs");
                System.out.println(u);
                System.out.println(p);
                System.out.println(uname);
                System.out.println(passs);
                 
                if(u.equals(uname) && p.equals(passs)){
                    JOptionPane.showMessageDialog(this,"Logged in succesfully!");
                    this.dispose();
                    new pr2_8().setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Invalid credentials!!");
                }
            } 
            con.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        new pr2_8().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpRedirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpRedirectionActionPerformed
        // TODO add your handling code here:
        new pr2_4().setVisible(true);
    }//GEN-LAST:event_btnSignUpRedirectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pr2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pr2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pr2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pr2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pr2_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUpRedirection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
